// sidebars.js

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar from the docs root directory
    },
  ],
};

module.exports = sidebars;