// sidebars.js

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  xplorerGuidesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'xplorer-guides', // Generate sidebar from the 'xplorer-guides' directory
    },
  ],
};

module.exports = sidebars;